// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Goldpinger
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 3.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
