// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bloomberg/goldpinger/v3/pkg/models"
)

// CheckAllPodsOKCode is the HTTP code returned for type CheckAllPodsOK
const CheckAllPodsOKCode int = 200

/*CheckAllPodsOK Success, return response

swagger:response checkAllPodsOK
*/
type CheckAllPodsOK struct {

	/*
	  In: Body
	*/
	Payload *models.CheckAllResults `json:"body,omitempty"`
}

// NewCheckAllPodsOK creates CheckAllPodsOK with default headers values
func NewCheckAllPodsOK() *CheckAllPodsOK {

	return &CheckAllPodsOK{}
}

// WithPayload adds the payload to the check all pods o k response
func (o *CheckAllPodsOK) WithPayload(payload *models.CheckAllResults) *CheckAllPodsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check all pods o k response
func (o *CheckAllPodsOK) SetPayload(payload *models.CheckAllResults) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckAllPodsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
