// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bloomberg/goldpinger/v3/pkg/models"
)

// CheckServicePodsOKCode is the HTTP code returned for type CheckServicePodsOK
const CheckServicePodsOKCode int = 200

/*CheckServicePodsOK Success, return response

swagger:response checkServicePodsOK
*/
type CheckServicePodsOK struct {

	/*
	  In: Body
	*/
	Payload *models.CheckResults `json:"body,omitempty"`
}

// NewCheckServicePodsOK creates CheckServicePodsOK with default headers values
func NewCheckServicePodsOK() *CheckServicePodsOK {

	return &CheckServicePodsOK{}
}

// WithPayload adds the payload to the check service pods o k response
func (o *CheckServicePodsOK) WithPayload(payload *models.CheckResults) *CheckServicePodsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check service pods o k response
func (o *CheckServicePodsOK) SetPayload(payload *models.CheckResults) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckServicePodsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
