// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bloomberg/goldpinger/v3/pkg/models"
)

// ClusterHealthOKCode is the HTTP code returned for type ClusterHealthOK
const ClusterHealthOKCode int = 200

/*ClusterHealthOK Healthy cluster

swagger:response clusterHealthOK
*/
type ClusterHealthOK struct {

	/*
	  In: Body
	*/
	Payload *models.ClusterHealthResults `json:"body,omitempty"`
}

// NewClusterHealthOK creates ClusterHealthOK with default headers values
func NewClusterHealthOK() *ClusterHealthOK {

	return &ClusterHealthOK{}
}

// WithPayload adds the payload to the cluster health o k response
func (o *ClusterHealthOK) WithPayload(payload *models.ClusterHealthResults) *ClusterHealthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cluster health o k response
func (o *ClusterHealthOK) SetPayload(payload *models.ClusterHealthResults) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ClusterHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ClusterHealthServiceUnavailableCode is the HTTP code returned for type ClusterHealthServiceUnavailable
const ClusterHealthServiceUnavailableCode int = 503

/*ClusterHealthServiceUnavailable Unhealthy cluster

swagger:response clusterHealthServiceUnavailable
*/
type ClusterHealthServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ClusterHealthResults `json:"body,omitempty"`
}

// NewClusterHealthServiceUnavailable creates ClusterHealthServiceUnavailable with default headers values
func NewClusterHealthServiceUnavailable() *ClusterHealthServiceUnavailable {

	return &ClusterHealthServiceUnavailable{}
}

// WithPayload adds the payload to the cluster health service unavailable response
func (o *ClusterHealthServiceUnavailable) WithPayload(payload *models.ClusterHealthResults) *ClusterHealthServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cluster health service unavailable response
func (o *ClusterHealthServiceUnavailable) SetPayload(payload *models.ClusterHealthResults) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ClusterHealthServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
