// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CallStats call stats
//
// swagger:model CallStats
type CallStats struct {

	// check
	Check int64 `json:"check,omitempty"`

	// check all
	CheckAll int64 `json:"check_all,omitempty"`

	// ping
	Ping int64 `json:"ping,omitempty"`
}

// Validate validates this call stats
func (m *CallStats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CallStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CallStats) UnmarshalBinary(b []byte) error {
	var res CallStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
