// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckServicePodsParams creates a new CheckServicePodsParams object
// with the default values initialized.
func NewCheckServicePodsParams() *CheckServicePodsParams {

	return &CheckServicePodsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckServicePodsParamsWithTimeout creates a new CheckServicePodsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckServicePodsParamsWithTimeout(timeout time.Duration) *CheckServicePodsParams {

	return &CheckServicePodsParams{

		timeout: timeout,
	}
}

// NewCheckServicePodsParamsWithContext creates a new CheckServicePodsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckServicePodsParamsWithContext(ctx context.Context) *CheckServicePodsParams {

	return &CheckServicePodsParams{

		Context: ctx,
	}
}

// NewCheckServicePodsParamsWithHTTPClient creates a new CheckServicePodsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckServicePodsParamsWithHTTPClient(client *http.Client) *CheckServicePodsParams {

	return &CheckServicePodsParams{
		HTTPClient: client,
	}
}

/*CheckServicePodsParams contains all the parameters to send to the API endpoint
for the check service pods operation typically these are written to a http.Request
*/
type CheckServicePodsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check service pods params
func (o *CheckServicePodsParams) WithTimeout(timeout time.Duration) *CheckServicePodsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check service pods params
func (o *CheckServicePodsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check service pods params
func (o *CheckServicePodsParams) WithContext(ctx context.Context) *CheckServicePodsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check service pods params
func (o *CheckServicePodsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check service pods params
func (o *CheckServicePodsParams) WithHTTPClient(client *http.Client) *CheckServicePodsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check service pods params
func (o *CheckServicePodsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CheckServicePodsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
