// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bloomberg/goldpinger/v3/pkg/models"
)

// CheckServicePodsReader is a Reader for the CheckServicePods structure.
type CheckServicePodsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckServicePodsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCheckServicePodsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /check] checkServicePods", response, response.Code())
	}
}

// NewCheckServicePodsOK creates a CheckServicePodsOK with default headers values
func NewCheckServicePodsOK() *CheckServicePodsOK {
	return &CheckServicePodsOK{}
}

/*
CheckServicePodsOK describes a response with status code 200, with default header values.

Success, return response
*/
type CheckServicePodsOK struct {
	Payload *models.CheckResults
}

// IsSuccess returns true when this check service pods o k response has a 2xx status code
func (o *CheckServicePodsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this check service pods o k response has a 3xx status code
func (o *CheckServicePodsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check service pods o k response has a 4xx status code
func (o *CheckServicePodsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this check service pods o k response has a 5xx status code
func (o *CheckServicePodsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this check service pods o k response a status code equal to that given
func (o *CheckServicePodsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the check service pods o k response
func (o *CheckServicePodsOK) Code() int {
	return 200
}

func (o *CheckServicePodsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /check][%d] checkServicePodsOK %s", 200, payload)
}

func (o *CheckServicePodsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /check][%d] checkServicePodsOK %s", 200, payload)
}

func (o *CheckServicePodsOK) GetPayload() *models.CheckResults {
	return o.Payload
}

func (o *CheckServicePodsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CheckResults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
