// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bloomberg/goldpinger/v3/pkg/models"
)

// CheckAllPodsReader is a Reader for the CheckAllPods structure.
type CheckAllPodsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckAllPodsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckAllPodsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCheckAllPodsOK creates a CheckAllPodsOK with default headers values
func NewCheckAllPodsOK() *CheckAllPodsOK {
	return &CheckAllPodsOK{}
}

/*CheckAllPodsOK handles this case with default header values.

Success, return response
*/
type CheckAllPodsOK struct {
	Payload *models.CheckAllResults
}

func (o *CheckAllPodsOK) Error() string {
	return fmt.Sprintf("[GET /check_all][%d] checkAllPodsOK  %+v", 200, o.Payload)
}

func (o *CheckAllPodsOK) GetPayload() *models.CheckAllResults {
	return o.Payload
}

func (o *CheckAllPodsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CheckAllResults)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
