// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckAllPodsParams creates a new CheckAllPodsParams object
// with the default values initialized.
func NewCheckAllPodsParams() *CheckAllPodsParams {

	return &CheckAllPodsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckAllPodsParamsWithTimeout creates a new CheckAllPodsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckAllPodsParamsWithTimeout(timeout time.Duration) *CheckAllPodsParams {

	return &CheckAllPodsParams{

		timeout: timeout,
	}
}

// NewCheckAllPodsParamsWithContext creates a new CheckAllPodsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckAllPodsParamsWithContext(ctx context.Context) *CheckAllPodsParams {

	return &CheckAllPodsParams{

		Context: ctx,
	}
}

// NewCheckAllPodsParamsWithHTTPClient creates a new CheckAllPodsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckAllPodsParamsWithHTTPClient(client *http.Client) *CheckAllPodsParams {

	return &CheckAllPodsParams{
		HTTPClient: client,
	}
}

/*CheckAllPodsParams contains all the parameters to send to the API endpoint
for the check all pods operation typically these are written to a http.Request
*/
type CheckAllPodsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check all pods params
func (o *CheckAllPodsParams) WithTimeout(timeout time.Duration) *CheckAllPodsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check all pods params
func (o *CheckAllPodsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check all pods params
func (o *CheckAllPodsParams) WithContext(ctx context.Context) *CheckAllPodsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check all pods params
func (o *CheckAllPodsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check all pods params
func (o *CheckAllPodsParams) WithHTTPClient(client *http.Client) *CheckAllPodsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check all pods params
func (o *CheckAllPodsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CheckAllPodsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
