// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewClusterHealthParams creates a new ClusterHealthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClusterHealthParams() *ClusterHealthParams {
	return &ClusterHealthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClusterHealthParamsWithTimeout creates a new ClusterHealthParams object
// with the ability to set a timeout on a request.
func NewClusterHealthParamsWithTimeout(timeout time.Duration) *ClusterHealthParams {
	return &ClusterHealthParams{
		timeout: timeout,
	}
}

// NewClusterHealthParamsWithContext creates a new ClusterHealthParams object
// with the ability to set a context for a request.
func NewClusterHealthParamsWithContext(ctx context.Context) *ClusterHealthParams {
	return &ClusterHealthParams{
		Context: ctx,
	}
}

// NewClusterHealthParamsWithHTTPClient creates a new ClusterHealthParams object
// with the ability to set a custom HTTPClient for a request.
func NewClusterHealthParamsWithHTTPClient(client *http.Client) *ClusterHealthParams {
	return &ClusterHealthParams{
		HTTPClient: client,
	}
}

/* ClusterHealthParams contains all the parameters to send to the API endpoint
   for the cluster health operation.

   Typically these are written to a http.Request.
*/
type ClusterHealthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cluster health params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterHealthParams) WithDefaults() *ClusterHealthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cluster health params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterHealthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cluster health params
func (o *ClusterHealthParams) WithTimeout(timeout time.Duration) *ClusterHealthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster health params
func (o *ClusterHealthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster health params
func (o *ClusterHealthParams) WithContext(ctx context.Context) *ClusterHealthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster health params
func (o *ClusterHealthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster health params
func (o *ClusterHealthParams) WithHTTPClient(client *http.Client) *ClusterHealthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster health params
func (o *ClusterHealthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterHealthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
